%%
% liq_comp_calc.m
% October 23, 2010
% Alessondra Springmann
% inputs:
% liq_comp, mass_liquid, mass_solidified, mass_this_shell, new_mass_liquid
% solid, liquid

function new_liq = liq_comp_calc_HMH(liquid, mass_liquid,...
    mass_this_shell, solid, new_mass_liquid, j)

new_liq = (liquid(j-1,:) * mass_liquid...
    - mass_this_shell * solid(j,:))/new_mass_liquid;

function new_liq = liq_comp_calc_ECD(mass_liquid, liquid, solid, j)

liq_term = liquid(j-1,:) * (mass_liquid/new_mass_liquid)...
    * (1/1)...
    * (solid(j,:) *...
        (mass_solidified - mass_this_shell)...
        / (mass_solidified / liquid(j-1,:) )...
    );

new_liq = liquid(j) * (mass_liquid(j-1)/mass_liquid(j)) ...
    + liquid(j-1);